### ISSUE TITLE
Bug in subcritical powerplant report methods

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#1287]
### Discussed in https://github.com/IDAES/idaes-pse/discussions/1286

<div type='discussions-op-text'>

<sup>Originally posted by **finAtoZ** November 13, 2023</sup>
i run the  subcritical_power_plant.py without modification， but produced several errors.
the first error is 
<img width="1138" alt="5adc7898b47ce3abbf38f3e8f2bd909" src="https://github.com/IDAES/idaes-pse/assets/135591017/11b17a28-62c3-4536-95ee-61b546f0e35e">

and the second is 
```
Traceback (most recent call last):
  File "D:\IDAES\miniconda3\envs\idaes-pse\Lib\site-packages\idaes\models_extra\power_generation\flowsheets\subcritical_power_plant\subcritical_power_plant.py", line 2284, in <module>
    m_ss = main_steady_state()
  File "D:\IDAES\miniconda3\envs\idaes-pse\Lib\site-packages\idaes\models_extra\power_generation\flowsheets\subcritical_power_plant\subcritical_power_plant.py", line 325, in main_steady_state
    m = get_model(dynamic=False)
  File "D:\IDAES\miniconda3\envs\idaes-pse\Lib\site-packages\idaes\models_extra\power_generation\flowsheets\subcritical_power_plant\subcritical_power_plant.py", line 869, in get_model
    blr.initialize(m)
  File "D:\IDAES\miniconda3\envs\idaes-pse\lib\site-packages\idaes\models_extra\power_generation\flowsheets\subcritical_power_plant\subcritical_boiler_flowsheet.py", line 792, in initialize
    fs.aECON.initialize(outlvl=outlvl)
  File "D:\IDAES\miniconda3\envs\idaes-pse\lib\site-packages\idaes\core\base\unit_model.py", line 540, in initialize
    flags = blk.initialize_build(*args, **kwargs)
  File "D:\IDAES\miniconda3\envs\idaes-pse\lib\site-packages\idaes\models_extra\power_generation\unit_models\boiler_heat_exchanger_2D.py", line 3219, in initialize_build
    res = opt.solve(blk, tee=slc.tee)
  File "D:\IDAES\miniconda3\envs\idaes-pse\lib\site-packages\pyomo\opt\base\solvers.py", line 627, in solve
    raise ApplicationError("Solver (%s) did not exit normally" % self.name)
pyomo.common.errors.ApplicationError: Solver (ipopt) did not exit normally
```
the two errors appeared in different pc.</div>

**Comment by ksbeattie** [comment]
@MAZamarripa any progress on this?
