### ISSUE TITLE
degrees_of_freedom error with inequity constraint

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#13]
when I use degrees_of_freedom , the following error occurs.
AttributeError: 'NoneType' object has no attribute 'is_relational', 
I guess the inequity constraint leads to this issue.

**Comment by eslickj** [comment]
I don't think it is a problem with inequalities, at least not all of them.  It works for me in a model with inequlities. Can you post the full traceback?

**Comment by TheHuangs** [comment]
@eslickj ，please try the model attached.
[gams.zip](https://github.com/IDAES/idaes-pse/files/3311176/gams.zip)

**Comment by eslickj** [comment]
It works for me.  It says that has -6 degrees of freedom.  I'm not sure what the problem is here.  Maybe it's a pyomo version issue.  Can you post all the output you get when you run the problem?

**Comment by TheHuangs** [comment]
Traceback (most recent call last):

  File "<ipython-input-4-ae4de889daf3>", line 1, in <module>
    runfile('E:/Codes/LiQian/GAMS_Files/gams.py', wdir='E:/Codes/LiQian/GAMS_Files')

  File "c:\python36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "c:\python36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Codes/LiQian/GAMS_Files/gams.py", line 207, in <module>
    print(degrees_of_freedom(m))

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 100, in degrees_of_freedom
    return count_free_variables(blk) - count_equality_constraints(blk)

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 88, in count_free_variables
    return len(free_variables_in_active_equalities_set(blk))

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 129, in free_variables_in_active_equalities_set
    for c in active_equalities(blk):

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 81, in active_equalities
    if o.upper == o.lower: yield o

  File "c:\python36\lib\site-packages\pyomo\core\expr\numvalue.py", line 754, in __eq__
    return _generate_relational_expression(_eq, self, other)

  File "c:\python36\lib\site-packages\pyomo\core\expr\logical_expr.py", line 341, in _generate_relational_expression
    elif rhs.is_relational():

AttributeError: 'NoneType' object has no attribute 'is_relational'




runfile('E:/Codes/LiQian/GAMS_Files/gams.py', wdir='E:/Codes/LiQian/GAMS_Files')
Traceback (most recent call last):

  File "<ipython-input-5-ae4de889daf3>", line 1, in <module>
    runfile('E:/Codes/LiQian/GAMS_Files/gams.py', wdir='E:/Codes/LiQian/GAMS_Files')

  File "c:\python36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "c:\python36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Codes/LiQian/GAMS_Files/gams.py", line 207, in <module>
    print(degrees_of_freedom(m))

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 100, in degrees_of_freedom
    return count_free_variables(blk) - count_equality_constraints(blk)

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 88, in count_free_variables
    return len(free_variables_in_active_equalities_set(blk))

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 129, in free_variables_in_active_equalities_set
    for c in active_equalities(blk):

  File "c:\python36\lib\site-packages\idaes-1.0.1-py3.6.egg\idaes\ui\report.py", line 81, in active_equalities
    if o.upper == o.lower: yield o

  File "c:\python36\lib\site-packages\pyomo\core\expr\numvalue.py", line 754, in __eq__
    return _generate_relational_expression(_eq, self, other)

  File "c:\python36\lib\site-packages\pyomo\core\expr\logical_expr.py", line 341, in _generate_relational_expression
    elif rhs.is_relational():

AttributeError: 'NoneType' object has no attribute 'is_relational'
@eslickj

**Comment by andrewlee94** [comment]
Ah, I think I see the problem. @TheHuangs is using the release version of IDAES which has the old reporting methods.

The check `if o.upper == o.lower: ` only works for equality constraints, as one of `upper` or `lower` is `None` for an inequality. When I updated these methods, I modified this line to be:

`if if o.upper is not None and o.lower is not None and o.upper == o.lower:`

**Comment by TheHuangs** [comment]
@andrewlee94 ,Thank you, I have modified the associated lines. It works for me now.
