### ISSUE TITLE
Error "Helmholtz EoS external functions not available"

### ISSUE THREAD

**Issue by iPoberezhets** [IDAES/idaes-pse#1321]
Hi everyone. I installed the framework and decided to check if it worked correctly. To do this I ran the example "subcritical_boiler_src" (code below): 

```
import os

# Import Pyomo libraries
import pyomo.environ as pyo
from pyomo.network import Arc

# Import IDAES core
from idaes.core import FlowsheetBlock
from idaes.core.util.model_statistics import degrees_of_freedom
from idaes.core.util import model_serializer as ms
import idaes.core.util.scaling as iscale

# Import Unit Model Modules
from idaes.models.properties import iapws95

# Import IDAES standard unit model
import idaes.logger as idaeslog
from idaes.models_extra.power_generation.unit_models.drum import Drum
from idaes.models_extra.power_generation.unit_models.downcomer import Downcomer
from idaes.models_extra.power_generation.unit_models.waterwall_section import (
    WaterwallSection,
)
from idaes.models_extra.power_generation.properties.flue_gas_ideal import (
    FlueGasParameterBlock,
)

# import subcritical functions
import idaes.models_extra.power_generation.flowsheets.subcritical_power_plant.subcritical_boiler as sub


# Create a Concrete Model as the top level object
m = pyo.ConcreteModel()
# Add a flowsheet object to the model
m.fs = FlowsheetBlock(dynamic=False)
# Add property packages to flowsheet library
m.fs.prop_water = iapws95.Iapws95ParameterBlock()
m.fs.prop_gas = FlueGasParameterBlock()

# create drum, downcomer, waterwall section models and connections
sub.create_model(m)
# set inputs (equipment dimensions and inlet conditions)
sub.set_inputs(m)
# initialize each model at the time
sub.initialize(m, outlvl=0)
```
when I ran the code I got an error: 
```
2024-01-24 17:22:48 [ERROR] idaes.core.base.process_block: Failure in build: fs.prop_water
Traceback (most recent call last):
  File "C:\Users\IPoberejec\Anaconda3\lib\site-packages\idaes\core\base\process_block.py", line 41, in _rule_default
    b.build()
  File "C:\Users\IPoberejec\Anaconda3\lib\site-packages\idaes\models\properties\general_helmholtz\helmholtz_functions.py", line 1437, in build
    raise RuntimeError("Helmholtz EoS external functions not available")
RuntimeError: Helmholtz EoS external functions not available
ERROR: Constructing component 'fs.prop_water' from data=None failed:
RuntimeError: Helmholtz EoS external functions not available"
```
I thought it was due to poor performance between versions pyomo and IDAES but attempts to install an older version led to the same result. Does anyone know how to solve this problem with functions Helmholtz.

**Comment by iPoberezhets** [comment]
error log:

```
--------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [9], in <cell line: 36>()
     34 m.fs = FlowsheetBlock(dynamic=False)
     35 # Add property packages to flowsheet library
---> 36 m.fs.prop_water = iapws95.Iapws95ParameterBlock()
     37 m.fs.prop_gas = FlueGasParameterBlock()
     39 # create drum, downcomer, waterwall section models and connections

File ~\Anaconda3\lib\site-packages\pyomo\core\base\block.py:580, in _BlockData.__setattr__(self, name, val)
    575 if name not in self.__dict__:
    576     if isinstance(val, Component):
    577         #
    578         # Pyomo components are added with the add_component method.
    579         #
--> 580         self.add_component(name, val)
    581     else:
    582         #
    583         # Other Python objects are added with the standard __setattr__
    584         # method.
    585         #
    586         super(_BlockData, self).__setattr__(name, val)

File ~\Anaconda3\lib\site-packages\pyomo\core\base\block.py:1185, in _BlockData.add_component(self, name, val)
   1177     logger.debug(
   1178         "Constructing %s '%s' on %s from data=%s",
   1179         val.__class__.__name__,
   (...)
   1182         str(data),
   1183     )
   1184 try:
-> 1185     val.construct(data)
   1186 except:
   1187     err = sys.exc_info()[1]

File ~\Anaconda3\lib\site-packages\pyomo\core\base\block.py:2199, in Block.construct(self, data)
   2197                     obj.construct(data.get(name, None))
   2198         # Trigger the (normal) initialization of the block
-> 2199         self._getitem_when_not_present(_idx)
   2200 finally:
   2201     # We must allow that id(self) may no longer be in
   2202     # _BlockConstruction.data, as _getitem_when_not_present will
   2203     # have already removed the entry for scalar blocks (as the
   2204     # BlockData and the Block component are the same object)
   2205     if data is not None:

File ~\Anaconda3\lib\site-packages\pyomo\core\base\block.py:2119, in Block._getitem_when_not_present(self, idx)
   2116     data = None
   2118 try:
-> 2119     obj = self._rule(_block, idx)
   2120     # If the user returns a block, transfer over everything
   2121     # they defined into the empty one we created.  We do
   2122     # this inside the try block so that any abstract
   2123     # components declared by the rule have the opportunity
   2124     # to be initialized with data from
   2125     # _BlockConstruction.data as they are transferred over.
   2126     if obj is not _block and isinstance(obj, _BlockData):

File ~\Anaconda3\lib\site-packages\pyomo\core\base\initializer.py:316, in IndexedCallInitializer.__call__(self, parent, idx)
    314     return self._fcn(parent, *idx)
    315 else:
--> 316     return self._fcn(parent, idx)

File ~\Anaconda3\lib\site-packages\idaes\core\base\process_block.py:41, in _rule_default(b, *args)
     35 """
     36 Default rule for ProcessBlock, which calls build(). A different rule can
     37 be specified to add additional build steps, or to not call build at all
     38 using the normal rule argument to ProcessBlock init.
     39 """
     40 try:
---> 41     b.build()
     42 except Exception:
     43     logging.getLogger(__name__).exception(f"Failure in build: {b}")

File ~\Anaconda3\lib\site-packages\idaes\models\properties\general_helmholtz\helmholtz_functions.py:1437, in HelmholtzParameterBlockData.build(self)
   1435 """Populate the parameter block"""
   1436 if not self.available():
-> 1437     raise RuntimeError("Helmholtz EoS external functions not available")
   1438 super().build()
   1439 # Check if the specified component is supported

RuntimeError: Helmholtz EoS external functions not available
```

**Comment by lbianchi-lbl** [comment]
For future reference: 

- The Helmholtz EoS external functions are distributed as part of IDAES/idaes-ext
- The error described can happen if `idaes get-extensions` hasn't been run before running the flowsheet and/or test suite
- If this is the case, running `idaes get-extensions` should be enough to resolve the issue

@iPoberezhets feel free to chime in if the above didn't apply in your case and the error was caused and/or solved by something else.
