### ISSUE TITLE
Condenser unit model KeyError

### ISSUE THREAD

**Issue by anujad95** [IDAES/idaes-pse#135]
When the CO2_H2O_Ideal_VLE property package is used for simulating the condenser unit model (partial condenser), the following traceback is obtained:
```
Traceback (most recent call last):

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\block.py", line 543, in __setattr__
    self.add_component(name, val)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\block.py", line 1081, in add_component
    val.construct(data)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\block.py", line 1941, in construct
    self, self._rule, _block, _idx, self._options)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\misc.py", line 59, in apply_indexed_rule
    return rule(model)

  File "idaes\core\process_block.py", line 37, in _rule_default
    b.build()

  File "idaes\generic_models\unit_models\distillation\condenser.py", line 221, in build
    self._make_splits_partial_condenser()

  File "idaes\generic_models\unit_models\distillation\condenser.py", line 444, in _make_splits_partial_condenser
    rule=rule_liq_frac)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\block.py", line 543, in __setattr__
    self.add_component(name, val)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\block.py", line 1081, in add_component
    val.construct(data)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\expression.py", line 396, in construct
    key))

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\misc.py", line 57, in apply_indexed_rule
    return rule(model, *index)

  File "idaes\generic_models\unit_models\distillation\condenser.py", line 423, in rule_liq_frac
    for p in self._liquid_set)

  File "idaes\generic_models\unit_models\distillation\condenser.py", line 423, in <genexpr>
    for p in self._liquid_set)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\indexed_component.py", line 400, in __getitem__
    validated_index = self._validate_index(index)

  File "AppData\Local\Continuum\anaconda3\envs\idaes\lib\site-packages\pyomo\core\base\indexed_component.py", line 561, in _validate_index
    % ( idx, self.name, ))

KeyError: "Index '('Liq', 'CO2')' is not valid for indexed component 'fs.condenser.control_volume.properties_out[0.0].mole_frac_phase_comp'"
```

**Comment by andrewlee94** [comment]
@anujad95 This looks like an issue with the property package, not the condenser. The condenser is asking for `mole_frac_phase_comp`, which should be indexed by phase and component. However, it appears that this is not a valid index for the for `mole_frac_phase_comp`, which suggests that the property package got the indexing set(s) are wrong.

**Comment by andrewlee94** [comment]
@anujad95 Any update on this issue, and can we close it?

**Comment by anujad95** [comment]
@andrewlee94, i will look into this further and provide an update soon.

**Comment by andrewlee94** [comment]
@anujad95 Have you made any progress on identifying the source of this error message?

**Comment by ksbeattie** [comment]
@jghouse88 will take a look at this.

**Comment by ksbeattie** [comment]
This is related to: #96

**Comment by andrewlee94** [comment]
Closing due to lack of progress. If the issue still exists then someone can reopen.
