### ISSUE TITLE
Improve error reporting for `idaes get-extensions`

### ISSUE THREAD

**Issue by minhwvu** [IDAES/idaes-pse#152]
Hi John,

I am not sure if you have seen the error below. Please tell me how to fix it. Thanks!
```
(idaes-pse-1.8.0) PS C:\Users\ql0015> idaes get-extensions
Getting files...
Traceback (most recent call last):
  File "C:\Users\ql0015\AppData\Local\Continuum\miniconda3\Scripts\idaes-script.py", line 11, in <module>
    load_entry_point('idaes-pse==1.8.0.dev0', 'console_scripts', 'idaes')()
  File "c:\users\ql0015\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ql0015\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\ql0015\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ql0015\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ql0015\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ql0015\appdata\local\continuum\miniconda3\lib\site-packages\idaes_pse-1.8.0.dev0-py3.7.egg\idaes\commands\extensions.py", line 77, in get_extensions
    idaes.solvers.download_binaries(release, url, verbose, platform)
  File "c:\users\ql0015\appdata\local\continuum\miniconda3\lib\site-packages\idaes_pse-1.8.0.dev0-py3.7.egg\idaes\solvers.py", line 117, in download_binaries
    f.extractall(idaes.bin_directory)
  File "C:\Users\ql0015\AppData\Local\Continuum\miniconda3\lib\tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "C:\Users\ql0015\AppData\Local\Continuum\miniconda3\lib\tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "C:\Users\ql0015\AppData\Local\Continuum\miniconda3\lib\tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\ql0015\AppData\Local\Continuum\miniconda3\lib\tarfile.py", line 2155, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ql0015\\AppData\\Local\\idaes\\bin\\libgcc_s_seh-1.dll'
```

**Comment by ksbeattie** [comment]
Perhaps this could be improved by unpacking into a temp location, then moving/overwriting what is there, and issue a more readable warning if that fails.

**Comment by ksbeattie** [comment]
@eslickj, I'm going to put this on the backlog label and remove it from any release boards, in hope that someday we might get to it.
