### ISSUE TITLE
ValueError from report_numerical_issues() 

### ISSUE THREAD

**Issue by adam-a-a** [IDAES/idaes-pse#1522]
I am getting the following error when I try running `report_numerical_issues()` from the DiagnosticToolbox. I should note that this was working fine until I updated my WaterTAP environment--just haven't taken the time to identify potentially problematic dependencies.
```
Traceback (most recent call last):
  File "c:\redacted.py", line 450, in <module>
    dt.report_numerical_issues()
  File "C:\redacted\lib\site-packages\idaes\core\util\model_diagnostics.py", line 1501, in report_numerical_issues      
    warnings, next_steps = self._collect_numerical_warnings(jac=jac, nlp=nlp)
  File "C:\redacted\lib\site-packages\idaes\core\util\model_diagnostics.py", line 1246, in _collect_numerical_warnings  
    par_cons = check_parallel_jacobian(
  File "C:\redacted\lib\site-packages\idaes\core\util\model_diagnostics.py", line 3778, in check_parallel_jacobian      
    maxval = max(np.abs(vec.data))
ValueError: max() arg is an empty sequence
```
FYI @andrewlee94 @lbianchi-lbl

**Comment by andrewlee94** [comment]
@adam-a-a First thing, could you update your version of IDAES and see if the issue persists? From the line numbers it appears you version of IDAES is out-of-date (I suspect this will not fix the issue hwoever).

**Comment by lbianchi-lbl** [comment]
- As @andrewlee94 said, we need more info on the environment (`pip list` is a good starting point)
- As per @dallan-keylogic, there's a chance that #1395 might resolve this once merged

**Comment by dallan-keylogic** [comment]
@adam-a-a , do you have a file where you can replicate this? I could debug it live to figure out what the issue is.

**Comment by adam-a-a** [comment]
@dallan-keylogic I'll have to dig that up, but I think I realize why this happened. The model I was working with failed before going through initialization because of DOF > 0, and I was subsequently running `report_numerical_issues` on an uninitialized model, where there were likely variables without initial values.  

In the interim, I wonder if you want to run any old model, and before initializing, run `dt.report_numerical_issues`. I know that we aren't supposed to do this in the first place and really should initialize the model first before trying to report numerical issues. That said, maybe we want a more helpful exception to pop up if a user makes the same mistake that I did; e.g., "Consider initializing your model first as it seems that variables without initial values were passed in."

**Comment by lbianchi-lbl** [comment]
@dallan-keylogic has offered to look into this.

**Comment by andrewlee94** [comment]
The first thought is that we should check for initialized variables first and then raise and exception if any are found (or don't execute the rest of the checks), however, we would need to add a catch for uninitialized variables that also happen to not appear in any (active) constraints.

**Comment by lbianchi-lbl** [comment]
@dallan-keylogic will take a stab at this, targeting the Feb release.

**Comment by ksbeattie** [comment]
Fixed in #1564
