### ISSUE TITLE
AttributeError using IDAES 1.9.0

### ISSUE THREAD

**Issue by psalm3114** [IDAES/idaes-pse#297]
I newly installed Anaconda3 and IDAES 1.9.0. (solver&library v2.3.0 / pyomo 5.7.3 / python 3.8.5 windows 10)
When I run 'supercritical_steam_cycle.py' , it turns attributeerror as  below.
Could you please give me some advice ?

runfile('C:/ProgramData/Anaconda3/Lib/site-packages/idaes/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py', wdir='C:/ProgramData/Anaconda3/Lib/site-packages/idaes/power_generation/flowsheets/supercritical_steam_cycle')
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\Lib\site-packages\idaes\power_generation\flowsheets\supercritical_steam_cycle\supercritical_steam_cycle.py", line 33, in <module>
    from idaes.core import FlowsheetBlock  # Flowsheet class

  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\__init__.py", line 3, in <module>
    from .unit_model import UnitModelBlockData, UnitModelBlock

  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\unit_model.py", line 24, in <module>
    from .property_base import StateBlock

  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\property_base.py", line 43, in <module>
    from idaes.core.util import scaling as iscale

  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\util\scaling.py", line 34, in <module>
    from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyomo\contrib\pynumero\interfaces\pyomo_nlp.py", line 26, in <module>
    from ..sparse.block_matrix import BlockMatrix

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyomo\contrib\pynumero\sparse\__init__.py", line 11, in <module>
    from ..dependencies import numpy_available, scipy_available

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyomo\contrib\pynumero\dependencies.py", line 30, in <module>
    scipy_sparse.generate_import_warning('pyomo.contrib.pynumero')

AttributeError: module 'scipy.sparse' has no attribute 'generate_import_warning'

**Comment by psalm3114** [comment]
Thank you for your support. But it turns same error. 

(base) PS C:\Users\User> python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from idaes.power_generation.flowsheets.supercritical_steam_cycle.supercritical_steam_cycle import main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\power_generation\flowsheets\supercritical_steam_cycle\__init__.py", line 1, in <module>
    from idaes.power_generation.flowsheets.supercritical_steam_cycle.supercritical_steam_cycle import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\power_generation\flowsheets\supercritical_steam_cycle\supercritical_steam_cycle.py", line 33, in <module>
    from idaes.core import FlowsheetBlock  # Flowsheet class
  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\__init__.py", line 3, in <module>
    from .unit_model import UnitModelBlockData, UnitModelBlock
  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\unit_model.py", line 24, in <module>
    from .property_base import StateBlock
  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\property_base.py", line 43, in <module>
    from idaes.core.util import scaling as iscale
  File "C:\ProgramData\Anaconda3\lib\site-packages\idaes\core\util\scaling.py", line 34, in <module>
    from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyomo\contrib\pynumero\interfaces\pyomo_nlp.py", line 26, in <module>
    from ..sparse.block_matrix import BlockMatrix
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyomo\contrib\pynumero\sparse\__init__.py", line 11, in <module>
    from ..dependencies import numpy_available, scipy_available
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyomo\contrib\pynumero\dependencies.py", line 30, in <module>
    scipy_sparse.generate_import_warning('pyomo.contrib.pynumero')
AttributeError: module 'scipy.sparse' has no attribute 'generate_import_warning'

I could not find another version of python installed.
So I just  restored  window 10 and reinstall anaconda & idaes.
Then no errors anymore.  Thanks a lot!
