### ISSUE TITLE
Issues with advanced user installation

### ISSUE THREAD

**Issue by Andresj89** [IDAES/idaes-pse#386]
During an advanced user installation, I got the following errors after doing `pip install -r requirements-dev.txt`, using Python 3.9 on Windows 10:

```
Looking in indexes: https://pypi.python.org/simple/
Obtaining file:///C:/Users/calderoa/Documents/IDAES/idaes-pse (from -r requirements-dev.txt (line 30))
Requirement already satisfied: alabaster>=0.7.7 in c:\msys64\mingw64\lib\python3.7\site-packages (from -r requirements-dev.txt (line 6)) (0.7.12)
Collecting sphinx>=3.0.0 (from -r requirements-dev.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/6e/8b/6662db1f132fc32e9ad10e2441a17b7d67219d7394b570434bee8b420301/Sphinx-4.0.2-py3-none-any.whl
Collecting sphinx-rtd-theme (from -r requirements-dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/ac/24/2475e8f83519b54b2148d4a56eb1111f9cec630d088c3ffc214492c12107/sphinx_rtd_theme-0.5.2-py2.py3-none-any.whl
Collecting sphinxcontrib-napoleon>=0.5.0 (from -r requirements-dev.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/75/f2/6b7627dfe7b4e418e295e254bb15c3a6455f11f8c0ad0d43113f678049c3/sphinxcontrib_napoleon-0.7-py2.py3-none-any.whl
Collecting sphinx-argparse (from -r requirements-dev.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/06/2b/dfad6a1831c3aeeae25d8d3d417224684befbf45e10c7f2141631616a6ed/sphinx-argparse-0.2.5.tar.gz
Collecting pytest (from -r requirements-dev.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/a1/59/6821e900592fbe261f19d67e4def0cb27e52ef8ed16d9922c144961cc1ee/pytest-6.2.4-py3-none-any.whl
Collecting coverage (from -r requirements-dev.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/38/df/d5e67851e83948def768d7fb1a0fd373665b20f56ff63ed220c6cd16cb11/coverage-5.5.tar.gz
Collecting pytest-cov (from -r requirements-dev.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/ba/84/576b071aef9ac9301e5c0ff35d117e12db50b87da6f12e745e9c5f745cc2/pytest_cov-2.12.1-py2.py3-none-any.whl
Collecting pylint (from -r requirements-dev.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/b2/97/a584ca733493cba7baca670800e615ced77c7b22e663e2eed6f68c931b87/pylint-2.8.3-py3-none-any.whl
Collecting flake8 (from -r requirements-dev.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/fc/80/35a0716e5d5101e643404dabd20f07f5528a21f3ef4032d31a49c913237b/flake8-3.9.2-py2.py3-none-any.whl
Collecting jsonschema (from -r requirements-dev.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting jupyter_contrib_nbextensions (from -r requirements-dev.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/33/f0/6e2c00afda860f655fbf0f795f7310bdbf12122846344dfdc803fc7455d5/jupyter_contrib_nbextensions-0.5.1-py2.py3-none-any.whl
Collecting snowballstemmer==1.2.1 (from -r requirements-dev.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting addheader>=0.2.2 (from -r requirements-dev.txt (line 26))
  Downloading https://files.pythonhosted.org/packages/9e/de/54c7bbb301e3c12912edfa50add6769d954580b61b756bc71c52608fcbcc/addheader-0.2.3-py3-none-any.whl
Collecting backports.shutil_get_terminal_size (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting bunch (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
Collecting click<=7.1.2 (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Requirement already satisfied: colorama in c:\msys64\mingw64\lib\python3.7\site-packages (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30)) (0.4.1)
Collecting flask (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/54/4f/1b294c1a4ab7b2ad5ca5fc4a9a65a22ef1ac48be126289d97668852d4ab3/Flask-2.0.1-py3-none-any.whl
Collecting flask-cors (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/db/84/901e700de86604b1c4ef4b57110d4e947c218b9997adf5d38fa7da493bce/Flask_Cors-3.0.10-py2.py3-none-any.whl
Collecting jupyter (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/83/df/0f5dd132200728a86190397e1ea87cd76244e42d39ec5e88efd25b2abd7e/jupyter-1.0.0-py2.py3-none-any.whl
Collecting lxml (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz
Collecting matplotlib (from idaes-pse==1.11.0.dev0->-r requirements-dev.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/60/d3/286925802edaeb0b8834425ad97c9564ff679eb4208a184533969aa5fc29/matplotlib-3.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\bit_generator.pyx
    Traceback (most recent call last):
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\tools\cythonize.py", line 59, in process_pyx
        import Cython
    ModuleNotFoundError: No module named 'Cython'
    The above exception was the direct cause of the following exception:
    Traceback (most recent call last):
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\tools\cythonize.py", line 239, in <module>
        main()
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\tools\cythonize.py", line 235, in main
        find_process_files(root_dir)
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\tools\cythonize.py", line 226, in find_process_files      
        process(root_dir, fromfile, tofile, function, hash_db)
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\tools\cythonize.py", line 192, in process
        processor_function(fromfile, tofile)
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\tools\cythonize.py", line 66, in process_pyx
        raise OSError(msg) from e
    OSError: Cython needs to be installed in Python as a module
    Running from numpy source directory.
    Traceback (most recent call last):
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 154, in save_modules
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 195, in setup_context
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 250, in run_setup
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 45, in _execfile
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\setup.py", line 447, in <module>
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\setup.py", line 429, in setup_package
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\setup.py", line 235, in generate_cython
        print_raw()
    RuntimeError: Running cythonize failed!

During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\calderoa\AppData\Local\Temp\pip-install-ida1_ku9\matplotlib\setup.py", line 314, in <module>
        cmdclass=cmdclass,
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\__init__.py", line 144, in setup
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\__init__.py", line 139, in _install_setup_requires
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\dist.py", line 724, in fetch_build_eggs
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\pkg_resources\__init__.py", line 782, in resolve
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\pkg_resources\__init__.py", line 1065, in best_match       
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\pkg_resources\__init__.py", line 1077, in obtain
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\dist.py", line 791, in fetch_build_egg
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\command\easy_install.py", line 679, in easy_install
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\command\easy_install.py", line 705, in install_item
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\command\easy_install.py", line 890, in install_eggs
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\command\easy_install.py", line 1158, in build_and_install
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\command\easy_install.py", line 1144, in run_setup
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 253, in run_setup
      File "C:\msys64\mingw64\lib\python3.7\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 195, in setup_context
      File "C:\msys64\mingw64\lib\python3.7\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 166, in save_modules
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 141, in resume
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\_vendor\six.py", line 685, in reraise
        exec_ = getattr(moves.builtins, "exec")
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 154, in save_modules
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 195, in setup_context
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 250, in run_setup
      File "C:\msys64\mingw64\lib\python3.7\site-packages\setuptools-40.8.0-py3.7.egg\setuptools\sandbox.py", line 45, in _execfile
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\setup.py", line 447, in <module>
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\setup.py", line 429, in setup_package
      File "C:\Users\calderoa\AppData\Local\Temp\easy_install-rvyyspw4\numpy-1.21.0rc2\setup.py", line 235, in generate_cython
        print_raw()
    RuntimeError: Running cythonize failed!
    Edit setup.cfg to change the build options; suppress output with --quiet.
    BUILDING MATPLOTLIB
      matplotlib: yes [3.4.2]
          python: yes [3.7.4 (default, Jul 23 2019, 08:13:38)  [GCC 9.1.0 64 bit
                      (AMD64)]]
        platform: yes [win32]
           tests: no  [skipping due to configuration]
          macosx: no  [Mac OS-X only]
    Cythonizing sources
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\calderoa\AppData\Local\Temp\pip-install-ida1_ku9\matplotlib\
```
As suggested by @dangunter, I installed Cython and matplotlib manually, and then I installed `requirements-dev.txt`, which seems to fix the issue.

**Comment by jsiirola** [comment]
The error stems from pip trying to install mapplotlib from a source distribution in your pip cache.  That is in turn trying to build (again, from source) a prerelease of numpy (1.21.0rc2).  To build numpy, you need Cython.

That said, I am not at all clear why you ended up with a source distribution of matplotlib in your cache.  It is also not clear why you are getting a RC release of numpy, nor why pip is pulling down the source and not the binary wheels (there is one available for Py3.9 / windows).

Can you try running `pip cache purge` and then re-attempting the installation?

**Comment by Andresj89** [comment]
@jsiirola Thanks for the clarification. `pip cache purge` did the trick. The installation worked fine.
