### ISSUE TITLE
Problem Running Property Interrogator Tool

### ISSUE THREAD

**Issue by adam-a-a** [IDAES/idaes-pse#430]
While trying to run the Property Interrogator Tool for the RO model in Proteuslib, I found that I could no longer use the tool successfully. 

Here is an example of the implementation:
```
from pyomo.environ import ConcreteModel, units
from idaes.core import FlowsheetBlock, Solute, Solvent, LiquidPhase, Phase
from proteuslib.unit_models.reverse_osmosis_0D import ReverseOsmosis0D
from idaes.generic_models.properties.interrogator import PropertyInterrogatorBlock

m = ConcreteModel()
m.fs = FlowsheetBlock(default={"dynamic": False, "time_units": units.s})
m.fs.properties = PropertyInterrogatorBlock(default={
        "phase_list": {"Liq": LiquidPhase},
        "component_list": {"H2O": Solvent,
                           "NaCl": Solute}})
m.fs.unit = ReverseOsmosis0D(default={
    "property_package": m.fs.properties})
```
Here is the error that I get :
```
Traceback (most recent call last):
  File "C:/Users/adama/my-idaes-dev/idaes-pse/SANDBOX/SANDBOX/sim_prop_interrogator.py", line 27, in <module>
    m.fs.properties = PropertyInterrogatorBlock(default={
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\pyomo\core\base\block.py", line 542, in __setattr__
    self.add_component(name, val)
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\pyomo\core\base\block.py", line 1087, in add_component
    val.construct(data)
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\pyomo\core\base\block.py", line 1984, in construct
2021-07-19 13:31:40 [ERROR] idaes.core.process_block: Failure in build: fs.properties
Traceback (most recent call last):
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\idaes\core\process_block.py", line 37, in _rule_default
    b.build()
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\idaes\generic_models\properties\interrogator\properties_interrogator.py", line 82, in build
    raise Exception()
Exception
ERROR: Constructing component 'fs.properties' from data=None failed:
    Exception:
    self._getitem_when_not_present(_idx)
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\pyomo\core\base\block.py", line 1909, in _getitem_when_not_present
    obj = self._rule(_block, idx)
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\pyomo\core\base\util.py", line 313, in __call__
    return self._fcn(parent, idx)
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\idaes\core\process_block.py", line 37, in _rule_default
    b.build()
  File "C:\Users\adama\Anaconda3\envs\my-idaes-dev\lib\site-packages\idaes\generic_models\properties\interrogator\properties_interrogator.py", line 82, in build
    raise Exception()
Exception
```
I think the problem has something to do with my environment, but the `Exception` may need to be given a type and relevant error message.

**Comment by adam-a-a** [comment]
It seems that the issue had to do with my version of IDAES; I needed to version 1.11 but was using 1.10.1.
