### ISSUE TITLE
CI checks failing on Windows with pip error: ValueError: path is on mount D:, start on mount c:

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#439]
## Symptoms

GitHub Actions jobs on Windows fail at the `pip show` stage with errors similar to this:

```sh
   ERROR: Exception:
  Traceback (most recent call last):
    File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
      status = self.run(options, args)
    File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\pip\_internal\commands\show.py", line 46, in run
      results, list_files=options.files, verbose=options.verbose):
    File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\pip\_internal\commands\show.py", line 160, in print_results
      for i, dist in enumerate(distributions):
    File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\pip\_internal\commands\show.py", line 128, in search_packages_info
      files = sorted(os.path.relpath(p, dist.location) for p in files_iter)
    File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\pip\_internal\commands\show.py", line 128, in <genexpr>
      files = sorted(os.path.relpath(p, dist.location) for p in files_iter)
    File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\ntpath.py", line 584, in relpath
      path_drive, start_drive))
  ValueError: path is on mount 'D:', start on mount 'c:'
```

## Impact

- This was detected in #438 and #348 among others, but seems to be a general issue affecting other projects as well (see e.g. nawi-hub/proteuslib#184)

## Diagnosis

- The working hypothesis is that this is a regression introduced by a recent pip update, likely between 21.1.3 and 21.2.1, over the past few days
 - Compare e.g. the following checks runs:
   - From today, failing: https://github.com/IDAES/idaes-pse/actions/runs/1077397436
   - From the day before, passing: https://github.com/IDAES/idaes-pse/actions/runs/1073711234

## Prognosis

- A possible way to address this, at least in the short term, would be to pin the pip version before installing the rest of the packages
  - I'm working right now on a PR to test this solution that will be up shortly

**Comment by lbianchi-lbl** [comment]
This is fixed in the sense that it doesn't affect the CI checks anymore, but the underlying issue is presumably still in pip and is being monitored by me.
