### ISSUE TITLE
Error when running `idaes` commands: TypeError: __init__() got an unexpected keyword argument 'package_name'

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#696]
Originally reported by @elbashandy, this issue can occur when running any of the `idaes` commands from the command line:

```sh
$ idaes get_extensions
Traceback (most recent call last):
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\aaelbashandy\.conda\envs\idaes\Scripts\idaes.exe\__main__.py", line 4, in <module>
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\idaes\commands\__init__.py", line 18, in <module>
    from idaes.commands.base import command_base as cb
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\idaes\commands\base.py", line 79, in <module>
    def command_base(verbose, quiet):
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\click\decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\click\decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\click\core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

The cause for this is likely that the installed version of `click` is not compatible with the `package_name` option, introduced in Click 8.0. To verify this, run `pip show click`.

A quick solution is to update the installed version of `click`, e.g. by running `pip install click==8`.

**Comment by ksbeattie** [comment]
Probably best to force `click>=8`
