### ISSUE TITLE
register_idaes_currency_units failed in SSLW

### ISSUE THREAD

**Issue by ZedongPeng** [IDAES/idaes-pse#920]
I tried `import idaes.models.costing.SSLW` and it failed with 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/site-packages/idaes/models/costing/SSLW.py", line 205, in <module>
    class SSLWCostingData(FlowsheetCostingBlockData):
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/site-packages/idaes/models/costing/SSLW.py", line 208, in SSLWCostingData
    register_idaes_currency_units()
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/site-packages/idaes/core/base/costing_base.py", line 39, in register_idaes_currency_units
    "USD_CE500" in pyo.units._pint_registry
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/site-packages/pint/registry.py", line 289, in __getitem__
    return self.parse_expression(item)
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/site-packages/pint/registry.py", line 1118, in parse_expression
    input_string = string_preprocessor(input_string)
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/site-packages/pint/util.py", line 716, in string_preprocessor
    input_string = input_string.replace(",", "")
AttributeError: 'int' object has no attribute 'replace'
```
Is there anyway to fix it?

I am using Python 3.7.12 on MacOS with `idaes-pse=2.0.0.dev3`.

**Comment by andrewlee94** [comment]
Hi @ZedongPeng, looking at that traceback, the issue appears to be coming from the `pint` package which we use to handle unit conversions. Could you tell us which version of `pint` you are using?

**Comment by ZedongPeng** [comment]
```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
absl-py                   1.0.0                    pypi_0    pypi
addheader                 0.2.3                    pypi_0    pypi
alabaster                 0.7.12                     py_0    conda-forge
ampl-mp                   3.1.0             h131c384_1004    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anaconda-navigator        1.9.12                   py37_0
appdirs                   1.4.3                    pypi_0    pypi
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argh                      0.26.2                   pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py37h69ee0a8_2    conda-forge
astroid                   2.3.3                    py37_1    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.5                      pypi_0    pypi
babel                     2.8.0                    pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       pyhd8ed1ab_1003    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bidict                    0.21.0                     py_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
boto3                     1.14.13                  pypi_0    pypi
botocore                  1.17.13                  pypi_0    pypi
brotlipy                  0.7.0           py37h69ee0a8_1004    conda-forge
bunch                     1.0.1                    pypi_0    pypi
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
certifi                   2019.9.11                pypi_0    pypi
cffi                      1.15.1           py37haabf53d_0    conda-forge
chardet                   5.0.0            py37hf985489_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py37hf985489_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
cog-suspect               2.1.2                    pypi_0    pypi
coinbonmin                1.8.8                hcd59dc4_0    conda-forge
coincbc                   2.10.5               h9fab268_1    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     4.13.0           py37hf985489_1    conda-forge
conda-build               3.18.9                   py37_3
conda-env                 2.6.0                         1
conda-package-handling    1.8.1            py37h69ee0a8_1    conda-forge
conda-verify              3.4.2                      py_1
coramin                   0.1.1                    pypi_0    pypi
coverage                  6.4.2            py37h994c40b_0    conda-forge
cplex                     12.10.0.0                pypi_0    pypi
cryptography              37.0.1           py37hf6deb26_0
cvxpy                     1.1.18                   pypi_0    pypi
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h811a1a6_3    conda-forge
debugpy                   1.6.0            py37h0582d14_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.5.1            pyhd8ed1ab_0    conda-forge
dispatches                1.1.dev0                 pypi_0    pypi
dispatches-sample-data    22.6.28                  pypi_0    pypi
distlib                   0.3.0                    pypi_0    pypi
distro                    1.7.0                    pypi_0    pypi
dnspython                 1.16.0                   pypi_0    pypi
doc8                      0.9.1              pyhd8ed1ab_0    conda-forge
docloud                   1.0.375                  pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
docplex                   2.18.200                 pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
ecos                      2.0.10                   pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
fastcache                 1.1.0            py37h69ee0a8_4    conda-forge
fett                      0.3.2                    pypi_0    pypi
filelock                  3.7.1              pyhd8ed1ab_0    conda-forge
flask                     2.1.3              pyhd8ed1ab_0    conda-forge
flask-cors                3.0.10             pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
future                    0.18.2           py37hf985489_5    conda-forge
gdplib                    20.5.29.dev7+g9ed8765           dev_0    <develop>
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
ggmodels                  0.1.dev4+g090fd5c           dev_0    <develop>
giflib                    5.2.1                hbcb3906_2    conda-forge
glob2                     0.7                        py_0    conda-forge
glpk                      4.65                 ha8bbb54_2
gmp                       6.2.1                h2e338ed_0    conda-forge
gmpy2                     2.1.2            py37h60f582e_0    conda-forge
gridx-egret               0.5.2                    pypi_0    pypi
gridx-prescient           2.1                      pypi_0    pypi
gurobipy                  9.0.0                    pypi_0    pypi
icu                       58.2              h0a44026_1000    conda-forge
idaes-examples            1.13.0                   pypi_0    pypi
idaes-pse                 2.0.0.dev3               pypi_0    pypi
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py37hf985489_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
ipopt                     3.13.3               h80040f7_5    conda-forge
ipykernel                 6.15.1             pyh736e0ef_0    conda-forge
ipython                   7.33.0           py37hf985489_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.1              pyhd8ed1ab_0    conda-forge
isort                     4.3.21           py37hc8dfbb8_1    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.18.1           py37hf985489_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hac89ed1_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.7.2              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py37hf985489_7    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py37hf985489_0    conda-forge
jupyterlab                2.0.1                      py_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py37h229a17a_0    conda-forge
lazy-object-proxy         1.7.1            py37h69ee0a8_1    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libarchive                3.5.2                hbf7dfe4_3    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcxx                    14.0.6               hce7ea42_0    conda-forge
libdeflate                1.12                 hac89ed1_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               4.0.0           7_5_0_h1a10cd1_23    conda-forge
libgfortran4              7.5.0               h1a10cd1_23    conda-forge
libglib                   2.72.1               hfbcb929_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
liblief                   0.11.5               he49afe7_1    conda-forge
libopenblas               0.3.12          openmp_h63d9170_1    conda-forge
libpng                    1.6.37               h5a3d3bf_3    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libtiff                   4.4.0                h9847915_1    conda-forge
libwebp                   1.2.3                hf64df63_1    conda-forge
libwebp-base              1.2.3                hac89ed1_2    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.14               hbf8cd5e_0
libxslt                   1.1.35               h5b33f42_0
libzlib                   1.2.12               hfe4f2af_2    conda-forge
livereload                2.6.1                    pypi_0    pypi
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
lxml                      4.9.1            py37h994c40b_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
markupsafe                2.1.1            py37h69ee0a8_1    conda-forge
matplotlib                3.4.1            py37hf985489_0    conda-forge
matplotlib-base           3.4.1            py37hb018525_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
metis                     5.1.0             h2e338ed_1006    conda-forge
mistune                   0.8.4           py37h271585c_1005    conda-forge
mock                      4.0.3            py37hf985489_3    conda-forge
more-itertools            8.13.0             pyhd8ed1ab_0    conda-forge
mpc                       1.2.1                hbb51d92_0    conda-forge
mpfr                      4.1.0                h0f52abe_1    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py37h036c24d_1    conda-forge
mpmath                    1.1.0                    pypi_0    pypi
mumps-include             5.2.1               h694c41f_10    conda-forge
mumps-mpi                 5.2.1               h3ff7435_10    conda-forge
mumps-seq                 5.2.1               h0fefb41_10    conda-forge
mypy-protobuf             3.2.0                    pypi_0    pypi
navigator-updater         0.2.1                    py37_0
nbclient                  0.6.6              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nbsphinx                  0.8.9                    pypi_0    pypi
nbval                     0.9.6                    pypi_0    pypi
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.4                        py_1    conda-forge
nose                      1.3.7                    pypi_0    pypi
notebook                  6.4.12             pyha770c72_0    conda-forge
nrel-pysam                3.0.1                    pypi_0    pypi
numpy                     1.21.3           py37haefe36b_0    conda-forge
omlt                      0.3.1                    pypi_0    pypi
openblas                  0.3.12          openmp_h3f95352_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openmpi                   4.0.5                hebb22fb_3    conda-forge
openpyxl                  3.0.3                      py_0    conda-forge
openssl                   3.0.5                hfe4f2af_0    conda-forge
ortools                   9.2.9972                 pypi_0    pypi
osqp                      0.6.2.post5              pypi_0    pypi
packaging                 20.3                     pypi_0    pypi
pandas                    1.2.3            py37hff173d8_0    conda-forge
pandoc                    2.18                 h694c41f_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parmetis                  4.0.3             hdba7654_1005    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pbr                       5.9.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py37h1eb1bbc_0    conda-forge
pint                      0.10.1                     py_0    conda-forge
pip                       21.3.1                   pypi_0    pypi
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py37hf985489_4    conda-forge
ply                       3.11                     py37_0
port-for                  0.3.1                    pypi_0    pypi
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
prompt_toolkit            3.0.30               hd8ed1ab_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.1            py37h994c40b_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptscotch                  6.0.9                h21714ec_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-cpuinfo                7.0.0                    pypi_0    pypi
py-lief                   0.11.5           py37hd8d24ac_1    conda-forge
pybind11                  2.9.0            py37h737db71_0    conda-forge
pybind11-global           2.9.0            py37h737db71_0    conda-forge
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py37h69ee0a8_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pylint                    2.4.4                    py37_0
pymongo                   3.11.4                   pypi_0    pypi
pymp-pypi                 0.4.2                    pypi_0    pypi
pymumps                   0.3.2           py37ha5ffffd_1006    conda-forge
pymysql                   1.0.2              pyhd8ed1ab_0    conda-forge
pynumero_libraries        1.3              py37h1cf269a_0    conda-forge
pyodbc                    4.0.34           py37hc568d09_0    conda-forge
pyomo                     6.4.1                    pypi_0    pypi
pyomo.extras              3.3                 py37_182212    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_4    conda-forge
pyro4                     4.80               pyh9f0ad1d_0    conda-forge
pyrsistent                0.18.1           py37h69ee0a8_1    conda-forge
pysocks                   1.7.1            py37hf985489_5    conda-forge
pysperf                   0.1.dev62+g9d8536c           dev_0    <develop>
pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
pytest-benchmark          3.2.3                    pypi_0    pypi
pytest-cov                2.8.1                      py_0    conda-forge
pytest-runner             5.3.0                    pypi_0    pypi
python                    3.7.12          hf3644f1_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python-graphviz           0.20                     pypi_0    pypi
python-jsonrpc-server     0.3.4                    pypi_0    pypi
python-libarchive-c       4.0              py37hf985489_1    conda-forge
python-slugify            6.1.2              pyhd8ed1ab_0    conda-forge
python.app                2                        py37_9
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyutilib                  5.8.1.dev0                dev_0    <develop>
pyyaml                    6.0              py37h69ee0a8_4    conda-forge
pyzmq                     23.2.0           py37h573e605_0    conda-forge
qdldl                     0.1.5.post0              pypi_0    pypi
qmodels                   0.1.dev139+g63ffd2f           dev_0    <develop>
qt                        5.9.7                h93ee506_2    conda-forge
qtconsole                 5.3.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.1              pyha770c72_0    conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
rbfopt                    4.2.4                    pypi_0    pypi
readline                  8.1.2                h3899abd_0    conda-forge
requests                  2.22.0                   pypi_0    pypi
restructuredtext_lint     1.4.0              pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               hbbacdb1_2    conda-forge
rstcheck                  3.3.1              pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py37h994c40b_1007    conda-forge
s3transfer                0.3.3                    pypi_0    pypi
scalapack                 2.0.2             h85f7579_1009    conda-forge
scikit-learn              0.22.2.post1     py37h3dc85bc_0    conda-forge
scipy                     1.5.3            py37h04d6967_0    conda-forge
scotch                    6.0.9                h3da7401_2    conda-forge
scs                       3.2.0                    pypi_0    pypi
seaborn                   0.11.0               h694c41f_1    conda-forge
seaborn-base              0.11.0             pyhd8ed1ab_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
serpent                   1.41               pyhd8ed1ab_0    conda-forge
setuptools                59.8.0           py37hf985489_1    conda-forge
simpy                     4.0.1                    pypi_0    pypi
sip                       4.19.8          py37h0a44026_1000    conda-forge
six                       1.12.0                   pypi_0    pypi
snooty-lextudio           1.11.5                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    4.2.0              pyh6c4a22f_0    conda-forge
sphinx-autobuild          0.7.1                    pypi_0    pypi
sphinx-copybutton         0.4.0              pyhd8ed1ab_0    conda-forge
sphinx-rtd-theme          0.4.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.39.2               hd9f0692_0    conda-forge
statsmodels               0.13.2           py37h4de8ad1_0    conda-forge
stevedore                 3.5.0            py37hf985489_3    conda-forge
sympy                     1.5.1                    py37_0
tabulate                  0.8.7                    pypi_0    pypi
terminado                 0.15.0           py37hf985489_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tinydb                    4.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.2              py37h994c40b_0    conda-forge
tox                       3.23.0                   pypi_0    pypi
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.4            py37h994c40b_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
ujson                     1.35                     pypi_0    pypi
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
unixodbc                  2.3.10               h7b58acd_0    conda-forge
urllib3                   1.25.6                   pypi_0    pypi
virtualenv                20.0.8                   pypi_0    pypi
watchdog                  1.0.2                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.1.2              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
wrapt                     1.14.1           py37h994c40b_0    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlutils                   2.0.0                    pypi_0    pypi
xlwings                   0.18.0                   pypi_0    pypi
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               hfe4f2af_2    conda-forge
zstd                      1.5.2                ha9df2e0_2    conda-forge

```

**Comment by ZedongPeng** [comment]
I'll try to update it. Thanks.
