### ISSUE TITLE
No executable found for solver `ipopt` on Ubuntu 20.04

### ISSUE THREAD

**Issue by wigging** [IDAES/idaes-pse#957]
I'm trying to install IDAES on the following system where Python is installed via Miniconda.

```
Ubuntu 20.04.5 LTS x86_64
Linux 5.4.0-125-generic
Bash 5.0.17
Intel Xeon E5-2680 v3 (20) @ 2.499GHz
Python 3.10.4
```

Following the steps in the IDAES documentation for Linux, I ran the following commands and didn't notice any errors during the installation.

```
sudo apt-get install libgfortran5 libgomp1 liblapack3 libblas3

conda create --name idaes python

conda activate idaes

conda install --yes -c IDAES-PSE -c conda-forge idaes-pse

idaes get-extensions
```

Example Python script to run.

```python
from pyomo.environ import Objective, Constraint, value, SolverFactory
from pyomo.environ import ConcreteModel, Var

model = ConcreteModel()
model.x = Var()
model.y = Var()

model.obj = Objective(expr=model.x**2 + model.y**2)

model.con = Constraint(expr=model.x + model.y == 1)

status = SolverFactory('ipopt').solve(model, tee=True)  # tee=True shows the solver log

print('x =', value(model.x))
print('y =', value(model.y))
print('obj =', value(model.obj))
```

Errors reported from running the example are shown below.

```
WARNING: Could not locate the 'ipopt' executable, which is required for solver
    ipopt
Traceback (most recent call last):
  File "/home/cades/idaes-examples/example1.py", line 20, in <module>
    status = SolverFactory('ipopt').solve(model, tee=True)  # tee=True shows the solver log
  File "/home/cades/miniconda3/envs/idaes/lib/python3.10/site-packages/pyomo/opt/base/solvers.py", line 513, in solve
    self.available(exception_flag=True)
  File "/home/cades/miniconda3/envs/idaes/lib/python3.10/site-packages/pyomo/opt/solver/shellcmd.py", line 129, in available
    raise ApplicationError(msg % self.name)
pyomo.common.errors.ApplicationError: No executable found for solver 'ipopt'
```

It looks like the `ipopt` solver was not installed. Is there another step I'm supposed to do for Linux?

**Comment by lbianchi-lbl** [comment]
Hi @wigging, can you try using `from idaes.core.solvers import get_solver` instead of `SolverFactory`?
